### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by wk-well** [chomeyama/SiFiGAN#10]
Ask if the pre-trained model you expect to publish on a larger data set already exists？
If published, would be appreciated

**Comment by chomeyama** [comment]
OK, I will try training a SIFi-GAN model with LibriTTS-R and NUS-48E datasets.
Please wait about a week.

**Comment by chomeyama** [comment]
Sorry for the delay. I have just released the pretrained model.
Please check README!

**Comment by wk-well** [comment]
thank you very much ! ! !
