### ISSUE TITLE
Empty output on Inference with checkpoint 

### ISSUE THREAD

**Issue by BorisovMaksim** [chomeyama/SiFiGAN#11]
I am trying to run inference with checkpoint sifigan_libritts-r-clean+nus-48e_checkpoint-1000000steps.pkl
So, I generated features from test set of libritts-R 
`sifigan-extract-features audio=data/scp/libtitts-R.scp `
Next 
`sifigan-compute-statistics feats=data/scp/libritts_R.list stats=data/stats/libritts_r_clean+nus-48e_train_no_dev.joblib`
And finally 
`sifigan-decode generator=sifigan data=libti out_dir=exp/sifigan checkpoint_steps=1000000 f0_factors=[0.5,1.0,2.0]`
Which generates audio without sound (no errors are produced)
Can you help me?

**Comment by chomeyama** [comment]
Is there any wav file generated in the directory `exp/sifigan/wav/100000`?
If files are generated, what are their contents? Are they continuously silent or 0-second audio files?

**Comment by BorisovMaksim** [comment]
They are generated. Continuously silent.

пт, 21 июл. 2023 г., 12:44 Reo YONEYAMA ***@***.***>:

**Comment by BorisovMaksim** [comment]
Sometimes they are not completely silent. For example: 
[0018_000387_f2.00.zip](https://github.com/chomeyama/SiFiGAN/files/12123252/0018_000387_f2.00.zip)

**Comment by chomeyama** [comment]
OK, I see. The likely cause is that different statistics are used during training and inference.

The statistics file "libritts_r_clean+nus-48e_train_no_dev.joblib" is provided along with the published model. Please use that statistics file for decoding.

Therefore, you do not need to perform the following process:
`sifigan-compute-statistics feats=data/scp/libritts_R.list stats=data/stats/libritts_r_clean+nus-48e_train_no_dev.joblib`

But you should run a command like this:
```
sifigan-decode generator=sifigan data=libti out_dir=hogehoge checkpoint_path=s
ifigan_libritts-r-clean+nus-48e_checkpoint-1000000steps.pkl data.stats=data/stats/libritts-r-clean+nus-48e_train_no_dev.joblib
```

**Comment by BorisovMaksim** [comment]
It works now. Thanks!
