### ISSUE TITLE
Question about auxiliary features (BAP)

### ISSUE THREAD

**Issue by hcy71o** [chomeyama/SiFiGAN#16]
Thank you for your great work!

One question related to your another [paper](https://ieeexplore.ieee.org/document/10246854), have you ever tried replace BAP(3-dim) with MAP(21-dim) in SiFiGAN experiments? 
I wonder whether MAP outperforms BAP in the case of this model.

**Comment by chomeyama** [comment]
Thank you for your interest in my work!

To be honest, I have never compared BAP and MAP in SiFi-GAN. However, based on my experience, I think that switching from BAP to MAP can yield some improvement.
