### ISSUE TITLE
pre-trained model request

### ISSUE THREAD

**Issue by playdasegunda** [chomeyama/SiFiGAN#3]
Hello again, sorry to bother you, I was looking at your repositories and found this one that seems very interesting, just as the other one. I would like you to make the pretrained SiFiGAN model available, as well as the inference command in a "test.wav" file. Would it be possible? This is what I found, exclusively for music vocals. Thank you again. Regards, Lucas.

**Comment by chomeyama** [comment]
Hello! I am sorry to be late to prepare the `sifigan-anasyn` command to resynthesis from wav files.
Now I have uploaded a pretrained model and you can download it from the link in README.
Please check it!
