### ISSUE TITLE
About the commit that added `feature matching loss`

### ISSUE THREAD

**Issue by Hiroshiba** [chomeyama/SiFiGAN#5]
I read your paper, very interesting!
I was surprised that SiFiGAN does not use `feature matching loss`.
You added this loss in a [recent commit](https://github.com/chomeyama/SiFiGAN/commit/ad5fc99aa72593291484c6001bc20f0e20175315), what is the purpose of this?
(for comparison experiments?)

**Comment by chomeyama** [comment]
Thank you for your interest! 
As you know, I  initially trained SiFi-GAN w/o the feature matching (fm) loss following uSFGAN, which often performs better when fm loss is not used. However, I empirically found that fm loss helps SiFi-GAN to decrease the adversarial loss more rapidly, even with slightly better perceptual quality, at least when trained on the Namine Ritsu database and JVS music corpus.

I still don't know the fundamental reason why fm loss tends to lead to better performance in SiFi-GAN but not uSFGAN. However, I think the possible factors are the number of model parameters or datasets used for training.

**Comment by Hiroshiba** [comment]
So it looks like fm loss would be better in SiFi-GAN! I understood very well.

No idea why fm loss works differently for each model....
I can understand that the adv loss decreases faster because more hints are coming to Vocoder for faking the Discriminator, but I can't understand why there is a difference in quality change in each model...

I would like to close the issue, thank you!
