### ISSUE TITLE
自作音響モデルの出力を使って合成したときのノイズについて

### ISSUE THREAD

**Issue by nakasako** [chomeyama/SiFiGAN#9]
自作のデータセットで学習させたモデルを使い実験をしています。
anasyn.pyを使い、既存の音声ファイルからWORLD analysisを使って抽出した音響特徴量で推論した音声は大変高品質です。
同じモデルを使い、自分で作った音響モデルの出力のメル、cf0、uv、bapを使って出力させると、f = sample_rate / sample_rate、nを正の整数としたとき、nf Hzの信号が常時乗り続けてしまいます。
SignalGeneratorの出力は（エイリアシングが強く出ていることを除き）正常であることを確認しています。
何か考えられる原因はありますでしょうか？
（添付画像1枚目：SignalGeneratorの出力 / 2枚目：出力）
<img width="854" alt="スクリーンショット 2023-06-23 123954" src="https://github.com/chomeyama/SiFiGAN/assets/58562294/5f55f5ee-60b7-4fed-b6fe-4e69d063b326">
<img width="854" alt="スクリーンショット 2023-06-23 124006" src="https://github.com/chomeyama/SiFiGAN/assets/58562294/592303d7-5398-443d-b875-380de77e9e0d">

**Comment by chomeyama** [comment]
実験への試用ありがとうございます！

ノイジーになってしまう件についてですが，試しに，音響モデルから出力されたメル（スペクトル or ケプストラム）と，自然音声から抽出したメルを見比べてみていただけますか？
経験上，音響モデルにより出力されたメルの平滑化が，ノイジーさの主要因になっていると予想しております．

**Comment by nakasako** [comment]
お返事ありがとうございます！

上が本物のメル、下が音響モデルの出力のメルです。
気になるのは、ノイジーである訳ではなく、生成された波形はメルに関係なくsample_rate / sample_rate (Hz)とその整数倍音が同じピッチでずっと鳴り続けていることです。
メルが平滑でない場合はメルの平滑さに応じたノイズになると思うのですが、特にメルやF0のピッチも関係なく、今回で言うとsr=48,000Hz、hop=120なので400Hzがずっと鳴り続けています。

自分がanasyn.pyを参考に書いたコードが間違っている可能性も十分に考えられますが、本物のメルを入力すると正しく合成されるため、今のところ問題の切り分けが出来ておりません。

お手数ですが、何か手がかりを頂けると幸いです。
<img width="920" alt="スクリーンショット 2023-06-23 224840" src="https://github.com/chomeyama/SiFiGAN/assets/58562294/f3fd54c5-27d5-4991-abfe-7aa2e355f4c0">

**Comment by chomeyama** [comment]
メルやF0にも依らない定常的なノイズが乗る問題は経験したことがなく，現在の情報だけでは原因が絞ることができていないためもう少し情報を頂ければと思います！

念のため確認ですが，自然音声から抽出した音響特徴量と，音響モデルが出力した音響特徴量を用いた推論では，共通のコードを用いている前提で大丈夫でしょうか？
たとえば`anasyn.py`を参考にすると，137行目（https://github.com/chomeyama/SiFiGAN/blob/main/sifigan/bin/anasyn.py#L137）あたりからは２つの推論では共通でしょうか？
原因がボコーダ内部の処理にあるのか，音響特徴量の用意までの処理のどちらにあるのかを明確にできればと思います！

**Comment by nakasako** [comment]
f0_factorは使用していないので142行目からのコードと同じ処理になっております。
自分のプロジェクトの環境に142行目以降を移しての上記結果ですので、自分の移し方、またはクラスの初期化などに問題がある可能性を切り分けるため、次に時間が取れた時にSiFiGANのvenv環境の方で極力anasyn.pyに近いコードを使って自分のメルを合成させてみたいと思います。
来月頭までしばらく時間が取れないため、返信が少し遅れます。
よろしくお願い致します。

**Comment by nakasako** [comment]
こんにちは。
ふと思い立って別の音響モデルのメルで合成したところ、400Hzのノイズが消えました。
メル等のグラフを目視で確認したところそこまで大きな違いが無かったので原因は不明ですが、ひとまず前のモデルの出力が原因であるのは確定したため、ひとまずクローズさせて頂きます。
理由が判明したときにはまたご報告したいと思います。

**Comment by chomeyama** [comment]
承知いたしました．理由がわかったようでよかったです！
